Repository WildCodeSchool/tours-0320-php-ShareMyBrain, pull requests merged in 2020-04, with the labels that each got.

#3 Structure
  .DS_Store
  config/.DS_Store
  public/assets/css/style.css
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Correction done

#4 ajout BDD, modif GIT IGNORE/README
  .gitignore
  DBD-SHAREMYBRAIN-v2.sql
  README.md
  Simple - MVC.png
  simple-mvc.sql
Labels: Reviewed

#8 Navbar
  .DS_Store
  public/assets/css/style.css
  src/View/layout.html.twig
Labels: waiting for review
